export function GetRandomWord(){
const words = [ "hiša", "avto", "miza", "stol", "pes", "mačka", "kolo", "drevo", "cvet", "knjiga", "časopis",
"računalnik", "telefon", "okno", "vrata", "zid", "strop", "tla", "postelja", "blazina", "odeja",
"omara", "polica", "luč", "svetilka", "klop", "pot", "cesta", "pločnik", "most", "park", "trgovina",
"knjižnica", "muzej", "šola", "univerza", "bolnišnica", "ambulanta", "lekarnar", "zdravnik", "sestra",
"pacient", "zobozdravnik", "učitelj", "študent", "profesor", "sodnik", "odvetnik", "policist", "gasilec",
"kmet", "delavec", "inženir", "znanstvenik", "pisatelj", "pesnik", "slikar", "glasbenik", "pevka",
"igralec", "plesalec", "kuhar", "natakar", "prodajalec", "kupovalec", "človek", "ženska", "moški",
"otrok", "dojenček", "najstnik", "družina", "oče", "mati", "brat", "sestra", "dedek", "babica",
"stric", "teta", "nečak", "nečakinja", "bratranec", "sestrična", "prijatelj", "sosed", "znanec",
"ljubimec", "šef", "kolega", "delo", "služba", "zaposlitev", "podjetje", "firma", "pisarna", "sejna",
"soba", "mesto", "vas", "ulica", "naselje", "blagajna", "tržnica", "parkirišče", "igrišče", "vrtec",
"šport", "igra", "zabava", "ples", "glasba", "film", "televizija", "radio", "računalniška", "igra",
"knjiga", "revija", "časopis", "novica", "članek", "reportaža", "intervju", "pesem", "zgodba",
"roman", "strip", "slika", "fotografija", "video", "film", "oddaja", "serija", "program",
"prezentacija", "predavanje", "seminar", "delavnica", "konferenca", "sestanek", "praznovanje",
"obletnica", "rojstni", "dan", "poroka", "obred", "cerkev", "kapela", "džamija", "sinagoga",
"tempelj", "samostan", "menih", "duhovnik", "škof", "nadškof", "kardinal", "papež", "vera",
"religija", "bog", "duh", "svetnik", "prerok", "angel", "demon", "duša", "telo", "um",
"misel", "ideja", "predstava", "sanje", "želja", "upanje", "strah", "ljubezen", "sovraštvo",
"veselje", "žalost", "jeza", "mir", "vojna", "bitka", "boj", "pobeda", "poraz", "zmaga",
"trening", "vaja", "tekma", "športnik", "ekipa", "klub", "liga", "prvenstvo", "turnir",
"medalja", "pokala", "rekord", "rezultat", "točka", "gol", "koš", "zadetka", "strel",
"udarec", "met", "skok", "tek", "kolesarjenje", "plavanje", "smučanje", "deskanje",
"tenis", "nogomet", "košarka", "rokomet", "odbojka", "hokej", "atletika", "gimnastika",
"ples", "plesalka", "plesalec", "učitelj", "učiteljica", "vzgojiteljica", "vzgojitelj",
"predavatelj", "predavateljica", "študent", "študentka", "dijak", "dijakinja", "učenec",
"učenka", "knjiga", "učbenik", "zvezek", "pisalo", "svinčnik", "kulica", "radirka",
"škarje", "lepilo", "barvice", "čopič", "barva", "platno", "kamen", "les", "kovina",
"steklo", "plastika", "papir", "karton", "vreča", "škatla", "kozarec", "skodelica",
"krožnik", "vilica", "nož", "žlica", "posoda", "lonček", "štedilnik", "pečica", "mikrovalovna",
"pralni", "stroj", "pomivalni", "stroj", "likalnik", "sesalnik", "klima", "gretje",
"hladilnik", "zamrzovalnik", "ura", "koledar", "budilka", "termometer", "barometer",
"kompas", "zemljevid", "atlas", "svetilka", "žarnica", "baterija", "vtičnica",
"stikalo", "žica", "kabel", "računalnik", "laptop", "tablica", "telefon", "pameten",
"ura", "televizija", "daljinec", "kamera", "fotoaparat", "mikrofon", "zvočnik",
"slušalke", "monitor", "tiskalnik", "skener", "kopirni", "stroj", "projektor",
"modem", "usmerjevalnik", "mreža", "internet", "stran", "splet", "elektronska",
"pošta", "geslo", "račun", "uporabnik", "profil", "družabna", "mreža", "aplikacija",
"program", "datoteka", "mapa", "disk", "pomnilnik", "procesor", "grafična",
"kartica", "matična", "plošča", "napajalnik", "ventilator", "tipkovnica", "miška",
"zvočna", "kartica", "omrežna", "kartica", "adapter", "konektor", "modul", "sistem",
"programska", "oprema", "operacijski", "sistem", "aplikacija", "igre", "zabava",
"delo", "posel", "pisarna", "sestanek", "konferenca", "predstavitev", "seminar",
"delavnica", "predavanje", "trening", "izobraževanje", "znanje", "veščine", "certifikat",
"diploma", "izpit", "ocene", "učni", "načrt", "učbenik", "knjiga", "zvezek", "pisalo",
"radirka", "škarje", "lepilo", "čopič", "barva", "platno", "list", "miza", "stol",
"klop", "tabla", "kreda", "pisalo", "računalnik", "projektor", "zaslon", "kamera",
"mikrofon", "zvočnik", "pametna", "tabla", "internet", "omrežje", "spletna", "stran",
"uporabniško", "ime", "geslo", "e-pošta", "družabno", "omrežje", "blog", "forum",
"diskusija", "komentar", "ocena", "kritika", "članek", "novica", "reportaža", "intervju",
"raziskava", "anketa", "povzetek", "recenzija", "predavanje", "seminar", "delavnica",
"trening", "izobraževanje", "znanje", "veščine", "certifikat", "diploma", "izpit",
"ocena", "pohvala", "kritika", "napredovanje", "posledica", "uspeh", "neuspeh",
"zmaga", "poraz", "cilj", "načrt", "strategija", "akcija", "opravilo", "naloga",
"projekt", "tim", "sodelavec", "vodja", "podrejeni", "sodelovanje", "timsko",
"delo", "komunikacija", "pogajanje", "reševanje", "problemov", "timski", "duh",
"motivacija", "spodbuda", "pomoč", "podpora", "svetovanje", "mentorstvo",
"vzgoja", "izobraževanje", "trening", "tečaj", "delavnica", "seminar", "usposabljanje",
"nastop", "predstavitev", "govor", "razlaga", "demonstracija", "vaja", "primerjava",
"analiza", "kritika", "debatiranje", "razprava", "dialog", "argumentacija",
"zaključek", "sklep", "odločitev", "rešitev", "izvedba", "akcija", "realizacija",
"izvedba", "izdelek", "storitev", "rezultat", "učinek", "posledica", "vrednost",
"pomembnost", "kakovost", "standard", "merilo", "pravilo", "zakon", "norma",
"etika", "vrednota", "mnenje", "stališče", "argument", "dokaz", "obrazložitev",
"pravica", "svoboda", "odgovornost", "dolžnost", "možnost", "priložnost", "nevarnost",
"tveganje", "varnost", "zagotovilo", "zaupanje", "spoštovanje", "ljubezen",
"sočutje", "solidarnost", "pomoč", "podpora", "razumevanje", "prijateljstvo",
"partnerstvo", "sodelovanje", "skupnost", "družina", "otroci", "starši",
"stari", "starši", "dedki", "babice", "bratje", "sestre", "teti", "strici",
"nečaki", "nečakinje", "bratranci", "sestrične", "prijatelji", "znanci",
"sodelavci", "sosedje", "kolegi", "sotrudniki", "timski", "igralec", "igralka",
"igralec", "igralec", "gledališče", "gledalka", "gledalec", "gledalec", "zbor",
"orkester", "ansambel", "skupina", "ekipa", "klub", "društvo", "zveza", "organizacija",
"podjetje", "firma", "delovno", "mesto", "služba", "delovni", "odnos", "delovnik",
"pogodba", "plača", "premija", "dodatek", "nadomestilo", "odpoved", "premestitev",
"napredovanje", "kolektivni", "dogovor", "pogajanje", "sodelavec", "vodja",
"nadzornik", "šef", "podrejeni", "timski", "delavec", "zaposleni", "sodelavec",
"ekipa", "partner", "konkurent", "stranka", "kupcu", "stranka"];
    
  let index = Math.floor(Math.random() * words.length);
    while(words[index].length > 10){
        index = Math.floor(Math.random() * words.length); 
    }
  return words[index];
}
